package id.ac.ubaya.informatika.adv160419144week2

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.Navigation
import kotlinx.android.synthetic.main.fragment_main.*

class MainFragment : Fragment() {
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_main, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        btnStart.setOnClickListener{
            val playerName = editAnswer.text.toString()
            //MainFragmentDirections -> class generated by safeargs
            //Holds all actions arrow that defined previously on navigation graph
            val action = MainFragmentDirections.actionGameFragment(playerName)
            //To trigger navigation, simply call Navigation obj and navigate method to the action
            Navigation.findNavController(it).navigate(action)
        }
    }
}